package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "area")
public class Area implements java.io.Serializable {

	private static final long serialVersionUID = 7327969508204107297L;
	private Integer id_area;
	private String nombre_area;

	private Set<Movimientos> movimiento = new HashSet<Movimientos>(0);
	private Set<Equipo> equipo = new HashSet<Equipo>(0);

	public Area() {
	}

	public Area(int id_area, String nombre_area) {
		this.setId_area(id_area);
		this.setNombre_area(nombre_area);
	}

	public Area(int id_area, String nombre_area,
			Set<Movimientos> movimiento, Set<Equipo> equipo) {
		this.setId_area(id_area);
		this.setNombre_area(nombre_area);
		this.setMovimiento(movimiento);
		this.setEquipo(equipo);
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_area", unique = true, nullable = false)
	public Integer getId_area() {
		return id_area;
	}

	public void setId_area(Integer id_area) {
		this.id_area = id_area;
	}

	@Column(name = "nombre_area", length = 200)
	public String getNombre_area() {
		return nombre_area;
	}

	public void setNombre_area(String nombre_area) {
		this.nombre_area = nombre_area;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Movimientos> getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(Set<Movimientos> movimiento1) {
		this.movimiento = movimiento1;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Equipo> getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Set<Equipo> equipo) {
		this.equipo = equipo;
	}
}
