package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

	private static final long serialVersionUID = -7699337985031695314L;

	private Integer id_departamento;
	private String nombre_departamento;
	
	private Set<Movimientos> movimiento = new HashSet<Movimientos>(0);
	private Set<Equipo> equipo = new HashSet<Equipo>(0);

	public Departamento() {
	}

	public Departamento(int id_departamento, String nombre_departamento) {
		this.setId_departamento(id_departamento);
		this.setNombre_departamento(nombre_departamento);
	}

	public Departamento(int id_departamento, String nombre_departamento,
			Set<Departamento> departamentos) {
		this.setId_departamento(id_departamento);
		this.setNombre_departamento(nombre_departamento);
		this.setMovimiento(movimiento);
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_departamento", unique = true, nullable = false)
	public Integer getId_departamento() {
		return id_departamento;
	}

	public void setId_departamento(Integer id_departamento) {
		this.id_departamento = id_departamento;
	}

	@Column(name = "nombre_departamento", length = 200)
	public String getNombre_departamento() {
		return nombre_departamento;
	}

	public void setNombre_departamento(String nombre_departamento) {
		this.nombre_departamento = nombre_departamento;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Movimientos> getMovimiento() {
		return this.movimiento;
	}
	
	public void setMovimiento(Set<Movimientos> movimiento) {
		this.movimiento = movimiento;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Equipo> getEquipo() {
		return this.equipo;
	}
	
	public void setEquipo(Set<Equipo> equipo) {
		this.equipo = equipo;
	}

}
