package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sucursal generated by hbm2java
 */

/**Model Equipo
 * El model sirve para identificar la tabla de la base de datos especificando el nombre de la tabla
 * @author baruchhdz
 *
 */

@Entity
@Table(name = "equipo")
public class Equipo implements java.io.Serializable {

	
/**Se colocan las variables en private y los tipos de datos integer, string, date, etc.
 * 
 */
	private static final long serialVersionUID = -6826118809950979205L;

	private int id_equipo;
	private Date fecha;
	private String no_serie;
	private String modelo;
	private Monitor monitor;
	private Mouse mouse;
	private Nobreak nobreak;
	private Scanner scanner;
	private Teclado teclado;
	private Impresora impresora;
	private String nombre_equipo;
	private String antivirus;
	private Integer ip;
	private Sistemaoperativo sistemaoperativo;
	private Fabricante fabricante;
	private Paqueteria paqueteria;
	private Area area;
	private Departamento departamento;
	private Personal personal;
	private String observaciones;
	private Integer estatus;

	// private Movimientos movimientos;
	private Set<Tipomantenimiento> tipomantenimiento = new HashSet<Tipomantenimiento>(0);
	private Set<Movimientos> movimiento = new HashSet<Movimientos>(0);

	public Equipo() {

	}

	public Equipo(int id_equipo, Date fecha, String no_serie, String modelo,
			Monitor monitor, Mouse mouse, Nobreak nobreak, Scanner scanner,
			Teclado teclado, Impresora impresora, String nombre_equipo,
			String antivirus, int ip, Sistemaoperativo sistemaoperativo,
			Fabricante fabricante, Paqueteria paqueteria, Area area,
			Departamento departamento, Personal personal, String observaciones,
			Integer estatus, Movimientos movimientos,
			Set<Tipomantenimiento> tipomantenimiento,
			Set<Movimientos> movimiento) {
		this.id_equipo = id_equipo;
		this.fecha = fecha;
		this.no_serie = no_serie;
		this.modelo = modelo;
		this.monitor = monitor;
		this.mouse = mouse;
		this.nobreak = nobreak;
		this.scanner = scanner;
		this.teclado = teclado;
		this.impresora = impresora;
		this.nombre_equipo = nombre_equipo;
		this.antivirus = antivirus;
		this.ip = ip;
		this.sistemaoperativo = sistemaoperativo;
		this.personal = personal;
		this.fabricante = fabricante;
		this.paqueteria = paqueteria;
		this.observaciones = observaciones;
		this.estatus = estatus;
		this.setTipomantenimiento(tipomantenimiento);
		// this.movimientos = movimientos;
		this.movimiento = movimiento;
	}

	public Equipo(int id_equipo, Date fecha, String no_serie, String modelo,
			Monitor monitor, Mouse mouse, Nobreak nobreak, Scanner scanner,
			Teclado teclado, Impresora impresora, String nombre_equipo,
			String antivirus, int ip, Sistemaoperativo sistemaoperativo,
			Fabricante fabricante, Paqueteria paqueteria, Area area,
			Departamento departamento, Personal personal, String observaciones,
			Integer estatus) {
		this.id_equipo = id_equipo;
		this.fecha = fecha;
		this.no_serie = no_serie;
		this.modelo = modelo;
		this.monitor = monitor;
		this.mouse = mouse;
		this.nobreak = nobreak;
		this.scanner = scanner;
		this.teclado = teclado;
		this.impresora = impresora;
		this.nombre_equipo = nombre_equipo;
		this.antivirus = antivirus;
		this.ip = ip;
		this.sistemaoperativo = sistemaoperativo;
		this.personal = personal;
		this.fabricante = fabricante;
		this.paqueteria = paqueteria;
		this.observaciones = observaciones;
		this.estatus = estatus;
	}

	/**
	 * Se identifican los campos de la tabla equipo
	 * @return
	 */
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_equipo", unique = true, nullable = false)
	public Integer getId_equipo() {
		return id_equipo;
	}

	public void setId_equipo(int id_equipo) {
		this.id_equipo = id_equipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 16)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "no_serie", length = 200)
	public String getNo_serie() {
		return no_serie;
	}

	public void setNo_serie(String no_serie) {
		this.no_serie = no_serie;
	}

	@Column(name = "modelo", length = 200)
	public String getModelo() {
		return modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "nombre_equipo", length = 200)
	public String getNombre_equipo() {
		return nombre_equipo;
	}

	public void setNombre_equipo(String nombre_equipo) {
		this.nombre_equipo = nombre_equipo;
	}

	@Column(name = "antivirus", length = 2)
	public String getAntivirus() {
		return antivirus;
	}

	public void setAntivirus(String antivirus) {
		this.antivirus = antivirus;
	}

	@Column(name = "ip", length = 11)
	public Integer getIp() {
		return ip;
	}

	public void setIp(Integer ip) {
		this.ip = ip;
	}

	@Column(name = "observaciones", length = 2)
	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	/**
	 * Se relaciona uno a muchos con la tabla tipo mantenimiento y movimientos
	 * @return
	 */
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Tipomantenimiento> getTipomantenimiento() {
		return this.tipomantenimiento;
	}

	public void setTipomantenimiento(Set<Tipomantenimiento> tipomantenimiento) {
		this.tipomantenimiento = tipomantenimiento;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Movimientos> getMovimiento() {
		return movimiento;
	}

	public void setMovimiento(Set<Movimientos> movimiento) {
		this.movimiento = movimiento;
	}

	/*
	 * public Movimientos getMovimientos() { return this.movimientos; }
	 * 
	 * public void setMovimientos(Movimientos movimientos) { this.movimientos =
	 * movimientos; }
	 */
	
	
	/**
	 * Se relaciona equipos muchos a uno con las tablas sistema operativo, fabricante, paqueteria, area, departamento,
	 * mouse, teclado, personal, monitor, impresora, no break, 
	 * @return
	 */

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_so", nullable = false)
	public Sistemaoperativo getSistemaoperativo() {
		return sistemaoperativo;
	}

	public void setSistemaoperativo(Sistemaoperativo sistemaoperativo) {
		this.sistemaoperativo = sistemaoperativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fabricante", nullable = false)
	public Fabricante getFabricante() {
		return fabricante;
	}

	public void setFabricante(Fabricante fabricante) {
		this.fabricante = fabricante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paqueteria", nullable = false)
	public Paqueteria getPaqueteria() {
		return paqueteria;
	}

	public void setPaqueteria(Paqueteria paqueteria) {
		this.paqueteria = paqueteria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_area", nullable = false)
	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_departamento", nullable = false)
	public Departamento getDepartamento() {
		return departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personal", nullable = false)
	public Personal getPersonal() {
		return personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	// /////////dispositivos

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_monitor", nullable = false)
	public Monitor getMonitor() {
		return monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mouse", nullable = false)
	public Mouse getMouse() {
		return mouse;
	}

	public void setMouse(Mouse mouse) {
		this.mouse = mouse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nobreak", nullable = false)
	public Nobreak getNobreak() {
		return nobreak;
	}

	public void setNobreak(Nobreak nobreak) {
		this.nobreak = nobreak;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_scanner", nullable = false)
	public Scanner getScanner() {
		return scanner;
	}

	public void setScanner(Scanner scanner) {
		this.scanner = scanner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_teclado", nullable = false)
	public Teclado getTeclado() {
		return teclado;
	}

	public void setTeclado(Teclado teclado) {
		this.teclado = teclado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_impresora", nullable = false)
	public Impresora getImpresora() {
		return impresora;
	}

	public void setImpresora(Impresora impresora) {
		this.impresora = impresora;
	}

	/*
	 * public void addMovimientos(Movimientos mov) { this.setMovimientos(mov); }
	 * 
	 * public void addMovimientosRow(Movimientos mov) {
	 * this.setMovimientos(mov); }
	 */
	
	/**
	 * Se declara una funcion addMovimiento que sirve para insertar en 2 tablas sin regresar valor
	 * @param mov
	 */
	
	 public void addMovimiento(Movimientos mov) {
	        this.movimiento.add(mov);
	}
}
