package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "impresora")
public class Impresora implements java.io.Serializable {

	private static final long serialVersionUID = 8324112506693800420L;
	private Integer id_impresora;
	private String serie;
	private String modelo;
	private String tipo;

	private Fabricante fabricante;
	private Set<Equipo> equipo = new HashSet<Equipo>(0);

	public Impresora() {
	}

	public Impresora(int id_impresora, String serie, String modelo, String tipo) {
		this.setId_impresora(id_impresora);
		this.setSerie(serie);
		this.setModelo(modelo);
		this.setTipo(tipo);
	}

	public Impresora(int id_impresora, String serie, String modelo, String tipo,
			Fabricante fabricante, Set<Equipo> equipo) {
		this.setId_impresora(id_impresora);
		this.setSerie(serie);
		this.setModelo(modelo);
		this.setTipo(tipo);
		this.setFabricante(fabricante);
		this.setEquipo(equipo);
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_impresora", unique = true, nullable = false)
	public Integer getId_impresora() {
		return id_impresora;
	}

	public void setId_impresora(Integer id_impresora) {
		this.id_impresora = id_impresora;
	}

	@Column(name = "serie", length = 100)
	public String getSerie() {
		return serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "modelo", length = 100)
	public String getModelo() {
		return modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}
	
	@Column(name = "tipo", length = 100)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "impresora")
	public Set<Equipo> getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Set<Equipo> equipo) {
		this.equipo = equipo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fabricante", nullable = false)
	public Fabricante getFabricante() {
		return fabricante;
	}

	public void setFabricante(Fabricante fabricante) {
		this.fabricante = fabricante;
	}

}