package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "paqueteria")
public class Paqueteria implements java.io.Serializable {

	private static final long serialVersionUID = 5816569554879235664L;

	private Integer id_paqueteria;
    private String office;
    private String descripcion;

    public Paqueteria() {
    }

    public Paqueteria(Integer id_paqueteria, String office, String descripcion) {
    	this.id_paqueteria = id_paqueteria;
    	this.office = office;}

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id_paqueteria", unique = true, nullable = false)
    public Integer getId_paqueteria() {
	return this.id_paqueteria;
    }

    public void setId_paqueteria(Integer id_paqueteria) {
	this.id_paqueteria = id_paqueteria;
    }

    @Column(name = "office", length = 200)
    public String getOffice() {
	return this.office;
    }

    public void setOffice(String office) {
	this.office = office;
    }

    @Column(name = "descripcion", length = 255)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
    

 /* void setUsuarios(Set<Usuario> usuarios) {
	this.usuarios = usuarios;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "grupo")
    public Set<Usuario> getUsuarios() {
	return this.usuarios;
    }
    
    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "grupo_autoridad", catalog = "dbpizza", joinColumns = { @JoinColumn(name = "idgrupo", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idautoridad", nullable = false, updatable = false) })
    public Set<Autoridad> getAutoridads() {
	return this.autoridads;
    }

    public void setAutoridads(Set<Autoridad> autoridads) {
	this.autoridads = autoridads;
    }
*/
}
