package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "personal")
public class Personal implements java.io.Serializable {

	private static final long serialVersionUID = -290030382339126296L;

	private Integer id_personal;
	private String nombre;
	private String ap_paterno;
	private String ap_materno;
	private Integer estatus;

	private Set<Equipo> equipo = new HashSet<Equipo>(0);
    private Set<Movimientos> movimiento = new HashSet<Movimientos>(0);


	public Personal() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_personal", unique = true, nullable = false)
	public Integer getId_personal() {
		return this.id_personal;
	}

	public void setId_personal(Integer id_personal) {
		this.id_personal = id_personal;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ap_paterno", length = 200)
	public String getAp_paterno() {
		return this.ap_paterno;
	}

	public void setAp_paterno(String ap_paterno) {
		this.ap_paterno = ap_paterno;
	}

	@Column(name = "ap_materno", length = 200)
	public String getAp_materno() {
		return this.ap_materno;
	}

	public void setAp_materno(String ap_materno) {
		this.ap_materno = ap_materno;
	}

	@Column(name = "estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<Equipo> getEquipo() {
		return this.equipo;
	}

	public void setequipo(Set<Equipo> equipo) {
		this.equipo = equipo;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "personal")
	public Set<Movimientos> getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(Set<Movimientos> movimiento) {
		this.movimiento = movimiento;
	}

}
