package com.inventario.model;

// Generated Sep 25, 2012 3:42:21 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "tipo_mantenimiento")
public class Tipomantenimiento implements java.io.Serializable {

	private static final long serialVersionUID = -5890773128382252253L;

	private Integer id_tipo_mantenimiento;
	private Date fecha;
	private Date fecha2;
	private String tipo_mantenimiento;
	private String observacion;
	private String reparacion;
	private Integer estatus;

	private Equipo equipo;

	public Tipomantenimiento() {
	}

	public Tipomantenimiento(int id_tipo_mantenimiento, Date fecha, Date fecha2,
			String tipo_mantenimiento, String descripcion, String observacion, String reparacion,
			Integer estatus) {
		this.id_tipo_mantenimiento = id_tipo_mantenimiento;
		this.tipo_mantenimiento = tipo_mantenimiento;
		this.observacion = observacion;
		this.reparacion = reparacion;
		this.estatus = estatus;
	}

	public Tipomantenimiento(int id_tipo_mantenimiento,Equipo equipo, Date fecha, Date fecha2,
			String tipo_mantenimiento, String desripcion, String observacion, String reparacion,
			int estatus) {
		this.id_tipo_mantenimiento = id_tipo_mantenimiento;
		this.setEquipo(equipo);
		this.tipo_mantenimiento = tipo_mantenimiento;
		this.observacion = observacion;
		this.reparacion = reparacion;
		this.estatus = estatus;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tipo_mantenimiento", unique = true, nullable = false)
	public Integer getId_tipo_mantenimiento() {
		return this.id_tipo_mantenimiento;
	}

	public void setId_tipo_mantenimiento(Integer id_tipo_mantenimiento) {
		this.id_tipo_mantenimiento = id_tipo_mantenimiento;
	}

	@Column(name = "fecha", unique = true, nullable = false)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "fecha2", unique = true, nullable = false)
	public Date getFecha2() {
		return this.fecha2;
	}

	public void setFecha2(Date fecha2) {
		this.fecha2 = fecha2;
	}
	
	@Column(name = "tipo_mantenimiento", length = 200)
	public String getTipo_mantenimiento() {
		return this.tipo_mantenimiento;
	}

	public void setTipo_mantenimiento(String Tipo_mantenimiento) {
		this.tipo_mantenimiento = Tipo_mantenimiento;
	}

	@Column(name = "observacion", length = 255)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "reparacion", nullable = false)
	public String getReparacion() {
		return this.reparacion;
	}

	public void setReparacion(String reparacion) {
		this.reparacion = reparacion;
	}

	
	@Column(name = "estatus", nullable = false)
	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipo", nullable = false)
	public Equipo getEquipo() {
		return equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

}
